package com.shatteredpixel.shatteredpixeldungeon.custom.utils;

import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ActHPtoGetFood;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Adrenaline;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.AdrenalineSurge;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Amok;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.AnkhInvulnerability;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ArcaneArmor;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ArtifactRecharge;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Awareness;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Barkskin;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Barrier;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.BasicBuffs;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Berserk;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Bleeding;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Bless;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.BlobImmunity;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Blindness;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Burning;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Charm;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Chill;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Combo;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Corrosion;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Corruption;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.CounterBuff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Cripple;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Degrade;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Doom;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Dread;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Drowsy;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.EarthImbue;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Empulse;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.EnhancedRings;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.EquipLevelUp;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.EquipmentBuff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.FieldRation;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.FireImbue;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.FlavourBuff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Foresight;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Frost;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.FrostImbue;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Fury;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.GunSwap;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Haste;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Healing;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Hex;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.HoldFast;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Hunger;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Invisibility;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ItemBuff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Levitation;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.LifeLink;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Light;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.LockedFloor;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.LostInventory;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.MagicalSight;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.MagicalSleep;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.MagicImmune;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.MindVision;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Momentum;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Ooze;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.P90FullAuto;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Paralysis;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.PinCushion;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Poison;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Preparation;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.PrismaticGuard;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Recharging;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Regeneration;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Resizing;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.RevealedArea;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Roots;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ScrollEmpower;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Shadows;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.SiriusHeart;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Sleep;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Slow;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.SnipersMark;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.SoulMark;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Speed;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Stamina;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.StarShield;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.TalentSecondSight;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Terror;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.ToxicImbue;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Vertigo;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Vulnerable;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.WandEmpower;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.WellFed;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Weakness;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Buff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.Buff_Statistics;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.CardSelectorBuff;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.Core_Calling;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.HS2000_Shield;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.S_M82A1;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.Vector_Fire_Aura;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.DandelionOwner.VHS_Hack;

import java.util.ArrayList;

/**
 * 由 AsmBuffScanGenerator 扫描生成的 Buff 类列表。
 * 列出了所有具体的（非抽象的）Buff 子类。
 * BuffCatalog 使用此列表构建 Buff 图鉴。
 */
public class BuffScanner {
    public static ArrayList<Class<? extends Buff>> getAllBuffClasses() {
        ArrayList<Class<? extends Buff>> buffClasses = new ArrayList<>();

        // actors/buffs/ (顶层)
        buffClasses.add(ActHPtoGetFood.class);
        buffClasses.add(Adrenaline.class);
        buffClasses.add(AdrenalineSurge.class);
        buffClasses.add(Amok.class);
        buffClasses.add(AnkhInvulnerability.class);
        buffClasses.add(ArcaneArmor.class);
        buffClasses.add(ArtifactRecharge.class);
        buffClasses.add(Awareness.class);
        buffClasses.add(Barkskin.class);
        buffClasses.add(Barrier.class);
        buffClasses.add(BasicBuffs.class);
        buffClasses.add(Berserk.class);
        buffClasses.add(Bleeding.class);
        buffClasses.add(Bless.class);
        buffClasses.add(BlobImmunity.class);
        buffClasses.add(Blindness.class);
        buffClasses.add(Burning.class);
        buffClasses.add(Charm.class);
        buffClasses.add(Chill.class);
        buffClasses.add(Combo.class);
        buffClasses.add(Corrosion.class);
        buffClasses.add(Corruption.class);
        buffClasses.add(CounterBuff.class);
        buffClasses.add(Cripple.class);
        buffClasses.add(Degrade.class);
        buffClasses.add(Doom.class);
        buffClasses.add(Dread.class);
        buffClasses.add(Drowsy.class);
        buffClasses.add(EarthImbue.class);
        buffClasses.add(Empulse.class);
        buffClasses.add(EnhancedRings.class);
        buffClasses.add(EquipLevelUp.class);
        buffClasses.add(EquipmentBuff.class);
        buffClasses.add(FieldRation.class);
        buffClasses.add(FireImbue.class);
        buffClasses.add(FlavourBuff.class);
        buffClasses.add(Foresight.class);
        buffClasses.add(Frost.class);
        buffClasses.add(FrostImbue.class);
        buffClasses.add(Fury.class);
        buffClasses.add(GunSwap.class);
        buffClasses.add(Haste.class);
        buffClasses.add(Healing.class);
        buffClasses.add(Hex.class);
        buffClasses.add(HoldFast.class);
        buffClasses.add(Hunger.class);
        buffClasses.add(Invisibility.class);
        buffClasses.add(ItemBuff.class);
        buffClasses.add(Levitation.class);
        buffClasses.add(LifeLink.class);
        buffClasses.add(Light.class);
        buffClasses.add(LockedFloor.class);
        buffClasses.add(LostInventory.class);
        buffClasses.add(MagicalSight.class);
        buffClasses.add(MagicalSleep.class);
        buffClasses.add(MagicImmune.class);
        buffClasses.add(MindVision.class);
        buffClasses.add(Momentum.class);
        buffClasses.add(Ooze.class);
        buffClasses.add(P90FullAuto.class);
        buffClasses.add(Paralysis.class);
        buffClasses.add(PinCushion.class);
        buffClasses.add(Poison.class);
        buffClasses.add(Preparation.class);
        buffClasses.add(PrismaticGuard.class);
        buffClasses.add(Recharging.class);
        buffClasses.add(Regeneration.class);
        buffClasses.add(Resizing.class);
        buffClasses.add(RevealedArea.class);
        buffClasses.add(Roots.class);
        buffClasses.add(ScrollEmpower.class);
        buffClasses.add(Shadows.class);
        buffClasses.add(SiriusHeart.class);
        buffClasses.add(Sleep.class);
        buffClasses.add(Slow.class);
        buffClasses.add(SnipersMark.class);
        buffClasses.add(SoulMark.class);
        buffClasses.add(Speed.class);
        buffClasses.add(Stamina.class);
        buffClasses.add(StarShield.class);
        buffClasses.add(TalentSecondSight.class);
        buffClasses.add(Terror.class);
        buffClasses.add(ToxicImbue.class);
        buffClasses.add(Vertigo.class);
        buffClasses.add(Vulnerable.class);
        buffClasses.add(WandEmpower.class);
        buffClasses.add(WellFed.class);
        buffClasses.add(Weakness.class);

        // actors/buffs/DandelionOwner/
        buffClasses.add(Buff_Statistics.class);
        buffClasses.add(CardSelectorBuff.class);
        buffClasses.add(Core_Calling.class);
        buffClasses.add(HS2000_Shield.class);
        buffClasses.add(S_M82A1.class);
        buffClasses.add(Vector_Fire_Aura.class);
        buffClasses.add(VHS_Hack.class);

        return buffClasses;
    }
}
